// ============================================================
// PDF Report Generator - DICT Region V PMS
// ============================================================

import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import { ExportActivity } from "./google-sheets";
import { DICT_PROJECTS, MONTHS } from "./types";

export interface ReportConfig {
  title: string;
  subtitle?: string;
  projectCode?: string;
  provinceName?: string;
  fy: string;
  periodLabel: string;
  activities: ExportActivity[];
  generatedBy: string;
  generatedAt: Date;
}

export interface GeneratedReport {
  blob: Blob;
  filename: string;
}

interface RGB { r: number; g: number; b: number }

export async function generatePDFReport(config: ReportConfig): Promise<GeneratedReport> {
  const doc = new jsPDF({ orientation: "landscape", unit: "mm", format: "a4" });
  const project = config.projectCode ? DICT_PROJECTS.find(p => p.code === config.projectCode) : null;
  const primaryColor = hexToRgb(project?.color ?? "#1a56db");
  const PAGE_W = doc.internal.pageSize.getWidth();
  const PAGE_H = doc.internal.pageSize.getHeight();

  drawCoverPage(doc, config, project, primaryColor, PAGE_W, PAGE_H);
  doc.addPage();
  drawHeader(doc, config, project, primaryColor, PAGE_W);
  drawExecutiveSummary(doc, config, primaryColor, PAGE_W);

  if (config.activities.length > 0) {
    doc.addPage();
    drawHeader(doc, config, project, primaryColor, PAGE_W);
    drawActivitiesTable(doc, config, primaryColor);
  }

  doc.addPage();
  drawHeader(doc, config, project, primaryColor, PAGE_W);
  drawParticipantBreakdown(doc, config, primaryColor);

  doc.addPage();
  drawHeader(doc, config, project, primaryColor, PAGE_W);
  drawByProvinceSummary(doc, config, primaryColor);

  doc.addPage();
  drawHeader(doc, config, project, primaryColor, PAGE_W);
  drawByMonthChart(doc, config, primaryColor, PAGE_W, PAGE_H);

  doc.addPage();
  drawHeader(doc, config, project, primaryColor, PAGE_W);
  drawParticipantPieChart(doc, config, primaryColor, PAGE_W, PAGE_H);
  drawProvinceBarChart(doc, config, primaryColor, PAGE_W, PAGE_H);

  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    drawFooter(doc, config, i, pageCount, PAGE_W, PAGE_H);
  }

  const filename = buildFilename(config, project);
  return { blob: doc.output("blob"), filename };
}

function drawCoverPage(doc: jsPDF, config: ReportConfig, project: ReturnType<typeof DICT_PROJECTS.find>, color: RGB, pw: number, ph: number) {
  doc.setFillColor(color.r, color.g, color.b);
  doc.rect(0, 0, pw, 60, "F");
  doc.setFillColor(255, 255, 255);
  doc.circle(20, 30, 12, "F");
  doc.setFont("helvetica", "bold");
  doc.setFontSize(7);
  doc.setTextColor(color.r, color.g, color.b);
  doc.text("DICT", 20, 30, { align: "center", baseline: "middle" });
  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.text("Republic of the Philippines", 37, 22);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(13);
  doc.text("Department of Information and Communications Technology", 37, 30);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.text("Region V - Bicol", 37, 38);

  doc.setTextColor(40, 40, 40);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(24);
  doc.text(config.title, pw / 2, 90, { align: "center" });
  if (config.subtitle) {
    doc.setFont("helvetica", "normal");
    doc.setFontSize(14);
    doc.setTextColor(80, 80, 80);
    doc.text(config.subtitle, pw / 2, 102, { align: "center" });
  }

  if (project) {
    const badgeW = 80;
    doc.setFillColor(color.r, color.g, color.b);
    doc.roundedRect((pw - badgeW) / 2, 112, badgeW, 12, 4, 4, "F");
    doc.setTextColor(255, 255, 255);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(10);
    doc.text(project.name, pw / 2, 119, { align: "center" });
  }

  const boxes = [
    { label: "Fiscal Year", value: config.fy },
    { label: "Period", value: config.periodLabel },
    { label: "Province", value: config.provinceName ?? "All Provinces" },
    { label: "Total Activities", value: config.activities.length.toString() },
  ];
  const boxW = (pw - 40) / boxes.length;
  boxes.forEach((box, i) => {
    const x = 20 + i * boxW;
    doc.setFillColor(248, 249, 250);
    doc.roundedRect(x, 140, boxW - 4, 28, 3, 3, "F");
    doc.setDrawColor(color.r, color.g, color.b);
    doc.roundedRect(x, 140, boxW - 4, 28, 3, 3, "S");
    doc.setTextColor(100, 100, 100);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8);
    doc.text(box.label, x + (boxW - 4) / 2, 149, { align: "center" });
    doc.setTextColor(30, 30, 30);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(13);
    doc.text(box.value, x + (boxW - 4) / 2, 161, { align: "center" });
  });

  doc.setFont("helvetica", "italic");
  doc.setFontSize(8);
  doc.setTextColor(140, 140, 140);
  doc.text(`Generated by: ${config.generatedBy} | ${formatDate(config.generatedAt)}`, pw / 2, ph - 15, { align: "center" });
}

function drawHeader(doc: jsPDF, config: ReportConfig, project: ReturnType<typeof DICT_PROJECTS.find>, color: RGB, pw: number) {
  doc.setFillColor(color.r, color.g, color.b);
  doc.rect(0, 0, pw, 18, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(9);
  doc.text("DICT Region V - " + (project?.name ?? "Consolidated Report"), 10, 11);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  doc.text(config.periodLabel + " | " + config.fy, pw - 10, 11, { align: "right" });
}

function drawFooter(doc: jsPDF, config: ReportConfig, page: number, total: number, pw: number, ph: number) {
  doc.setDrawColor(200, 200, 200);
  doc.line(10, ph - 12, pw - 10, ph - 12);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(7);
  doc.setTextColor(140, 140, 140);
  doc.text("DICT Region V Program Management System", 10, ph - 7);
  doc.text(`Page ${page} of ${total}`, pw - 10, ph - 7, { align: "right" });
}

function drawExecutiveSummary(doc: jsPDF, config: ReportConfig, color: RGB, pw: number) {
  const activities = config.activities;
  const totalPax = sumParticipants(activities);
  const provinces = [...new Set(activities.map(a => a.provinceName))];
  let y = 28;

  doc.setFont("helvetica", "bold");
  doc.setFontSize(13);
  doc.setTextColor(30, 30, 30);
  doc.text("Executive Summary", 10, y);
  y += 10;

  const kpis = [
    { label: "Total Activities", value: activities.length },
    { label: "Total Participants", value: totalPax },
    { label: "Provinces", value: provinces.length },
    { label: "LGUs", value: [...new Set(activities.map(a => a.lguName).filter(Boolean))].length },
    { label: "Validated/Reported", value: activities.filter(a => a.status === "Validated" || a.status === "Reported").length },
  ];
  const cardW = (pw - 20) / kpis.length - 2;
  kpis.forEach((kpi, i) => {
    const x = 10 + i * (cardW + 2);
    doc.setFillColor(color.r, color.g, color.b);
    doc.roundedRect(x, y, cardW, 22, 2, 2, "F");
    doc.setTextColor(255, 255, 255);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(16);
    doc.text(kpi.value.toLocaleString(), x + cardW / 2, y + 12, { align: "center" });
    doc.setFont("helvetica", "normal");
    doc.setFontSize(7);
    doc.text(kpi.label, x + cardW / 2, y + 18, { align: "center" });
  });
  y += 30;

  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.setTextColor(30, 30, 30);
  doc.text("Participant Breakdown by Sector", 10, y);
  y += 4;

  const ngaM = sum(activities, a => a.participants.nga.male);
  const ngaF = sum(activities, a => a.participants.nga.female);
  const lguM = sum(activities, a => a.participants.lgu.male);
  const lguF = sum(activities, a => a.participants.lgu.female);
  const sucM = sum(activities, a => a.participants.suc.male);
  const sucF = sum(activities, a => a.participants.suc.female);
  const othM = sum(activities, a => a.participants.others.male);
  const othF = sum(activities, a => a.participants.others.female);

  autoTable(doc, {
    startY: y,
    head: [["Sector", "Male", "Female", "Total", "% of Total"]],
    body: [
      ["NGA", ngaM, ngaF, ngaM + ngaF, pct(ngaM + ngaF, totalPax)],
      ["LGU", lguM, lguF, lguM + lguF, pct(lguM + lguF, totalPax)],
      ["SUC", sucM, sucF, sucM + sucF, pct(sucM + sucF, totalPax)],
      ["Others", othM, othF, othM + othF, pct(othM + othF, totalPax)],
      ["TOTAL", ngaM + lguM + sucM + othM, ngaF + lguF + sucF + othF, totalPax, "100%"],
    ],
    styles: { fontSize: 9, cellPadding: 3 },
    headStyles: { fillColor: [color.r, color.g, color.b], textColor: [255, 255, 255], fontStyle: "bold" },
    alternateRowStyles: { fillColor: [248, 248, 248] },
    margin: { left: 10, right: 10 },
  });
}

function drawActivitiesTable(doc: jsPDF, config: ReportConfig, color: RGB) {
  let y = 28;
  doc.setFont("helvetica", "bold");
  doc.setFontSize(13);
  doc.setTextColor(30, 30, 30);
  doc.text("Activity Records", 10, y);

  const rows = config.activities.map(a => {
    const total =
      a.participants.nga.male + a.participants.nga.female +
      a.participants.lgu.male + a.participants.lgu.female +
      a.participants.suc.male + a.participants.suc.female +
      a.participants.others.male + a.participants.others.female;
    
    // Clean and format text for better readability
    const monthText = MONTHS[a.month - 1]?.slice(0, 3) ?? String(a.month);
    const lguText = a.lguName || "N/A";
    const titleText = a.activityTitle.length > 35 
      ? a.activityTitle.slice(0, 32) + "..." 
      : a.activityTitle;
    const venueText = a.venue.length > 25 
      ? a.venue.slice(0, 22) + "..." 
      : a.venue;
    
    return [
      monthText,
      a.provinceName,
      lguText,
      titleText,
      venueText,
      a.modeOfConduct,
      total.toLocaleString(),
      a.status,
    ];
  });

  autoTable(doc, {
    startY: y + 4,
    head: [["Month", "Province", "LGU", "Activity Title", "Venue", "Mode", "Participants", "Status"]],
    body: rows,
    styles: { 
      fontSize: 7.5, 
      cellPadding: 2.5, 
      overflow: "linebreak",
      valign: "middle"
    },
    headStyles: { 
      fillColor: [color.r, color.g, color.b], 
      textColor: [255, 255, 255], 
      fontStyle: "bold",
      halign: "center"
    },
    alternateRowStyles: { fillColor: [248, 248, 250] },
    columnStyles: {
      0: { cellWidth: 14, halign: "center" },
      1: { cellWidth: 22 },
      2: { cellWidth: 25 },
      3: { cellWidth: 60 },
      4: { cellWidth: 45 },
      5: { cellWidth: 22, halign: "center" },
      6: { cellWidth: 20, halign: "right", fontStyle: "bold" },
      7: { cellWidth: 20, halign: "center" },
    },
    margin: { left: 10, right: 10 },
  });
}

function drawParticipantBreakdown(doc: jsPDF, config: ReportConfig, color: RGB) {
  let y = 28;
  doc.setFont("helvetica", "bold");
  doc.setFontSize(13);
  doc.setTextColor(30, 30, 30);
  doc.text("Participant Breakdown by Activity", 10, y);

  const rows = config.activities.map(a => {
    const p = a.participants;
    const total = p.nga.male + p.nga.female + p.lgu.male + p.lgu.female +
      p.suc.male + p.suc.female + p.others.male + p.others.female;
    
    // Clean title text
    const titleText = a.activityTitle.length > 30 
      ? a.activityTitle.slice(0, 27) + "..." 
      : a.activityTitle;
    
    return [
      titleText,
      a.provinceName,
      p.nga.male,
      p.nga.female,
      p.lgu.male,
      p.lgu.female,
      p.suc.male,
      p.suc.female,
      p.others.male,
      p.others.female,
      total,
    ];
  });

  autoTable(doc, {
    startY: y + 4,
    head: [["Activity", "Province", "NGA M", "NGA F", "LGU M", "LGU F", "SUC M", "SUC F", "Oth M", "Oth F", "Total"]],
    body: rows,
    styles: { 
      fontSize: 7, 
      cellPadding: 2, 
      halign: "center",
      valign: "middle"
    },
    headStyles: { 
      fillColor: [color.r, color.g, color.b], 
      textColor: [255, 255, 255], 
      fontStyle: "bold",
      fontSize: 7
    },
    alternateRowStyles: { fillColor: [248, 248, 250] },
    columnStyles: {
      0: { halign: "left", cellWidth: 65 },
      1: { halign: "left", cellWidth: 25 },
      10: { fontStyle: "bold", fillColor: [240, 240, 240] }
    },
    margin: { left: 10, right: 10 },
  });
}

function drawByProvinceSummary(doc: jsPDF, config: ReportConfig, color: RGB) {
  let y = 28;
  doc.setFont("helvetica", "bold");
  doc.setFontSize(13);
  doc.setTextColor(30, 30, 30);
  doc.text("Summary by Province", 10, y);

  const byProv: Record<string, { count: number; participants: number }> = {};
  for (const a of config.activities) {
    if (!byProv[a.provinceName]) byProv[a.provinceName] = { count: 0, participants: 0 };
    byProv[a.provinceName].count++;
    byProv[a.provinceName].participants +=
      a.participants.nga.male + a.participants.nga.female +
      a.participants.lgu.male + a.participants.lgu.female +
      a.participants.suc.male + a.participants.suc.female +
      a.participants.others.male + a.participants.others.female;
  }
  
  const total = Object.values(byProv).reduce(
    (s, v) => ({ count: s.count + v.count, participants: s.participants + v.participants }),
    { count: 0, participants: 0 }
  );
  
  // Sort by activity count descending
  const rows = Object.entries(byProv)
    .sort(([, a], [, b]) => b.count - a.count)
    .map(([prov, d]) => [
      prov,
      d.count,
      d.participants.toLocaleString(),
      pct(d.count, total.count),
      pct(d.participants, total.participants)
    ]);

  autoTable(doc, {
    startY: y + 4,
    head: [["Province", "Activities", "Participants", "% Activities", "% Participants"]],
    body: rows,
    foot: [["TOTAL", total.count, total.participants.toLocaleString(), "100%", "100%"]],
    styles: { 
      fontSize: 9, 
      cellPadding: 3,
      valign: "middle"
    },
    headStyles: { 
      fillColor: [color.r, color.g, color.b], 
      textColor: [255, 255, 255], 
      fontStyle: "bold",
      halign: "center"
    },
    footStyles: { 
      fillColor: [color.r, color.g, color.b], 
      textColor: [255, 255, 255],
      fontStyle: "bold",
      halign: "center"
    },
    alternateRowStyles: { fillColor: [248, 248, 248] },
    columnStyles: {
      0: { halign: "left", fontStyle: "bold" },
      1: { halign: "center" },
      2: { halign: "right" },
      3: { halign: "center" },
      4: { halign: "center" },
    },
    margin: { left: 10, right: 10 },
  });
}

function drawByMonthChart(doc: jsPDF, config: ReportConfig, color: RGB, pw: number, ph: number) {
  let y = 28;
  doc.setFont("helvetica", "bold");
  doc.setFontSize(13);
  doc.setTextColor(30, 30, 30);
  doc.text("Monthly Activity Trend", 10, y);
  
  // Add subtitle
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(100, 100, 100);
  doc.text("Number of activities conducted per month", 10, y + 6);
  y += 12;

  const byMonth: Record<number, number> = {};
  for (const a of config.activities) {
    byMonth[a.month] = (byMonth[a.month] || 0) + 1;
  }
  const maxVal = Math.max(...Object.values(byMonth), 1);
  const chartX = 20, chartY = y, chartW = pw - 40, chartH = 70;
  const barW = (chartW / 12) - 6;

  // Draw chart background
  doc.setFillColor(250, 250, 250);
  doc.roundedRect(chartX - 5, chartY - 5, chartW + 10, chartH + 20, 3, 3, "F");

  // Draw grid lines
  doc.setDrawColor(220, 220, 220);
  doc.setLineWidth(0.3);
  for (let i = 0; i <= 4; i++) {
    const gridY = chartY + (chartH / 4) * i;
    doc.line(chartX, gridY, chartX + chartW, gridY);
    // Add value labels on Y-axis
    const val = Math.round(maxVal * (1 - i / 4));
    doc.setFontSize(7);
    doc.setTextColor(120, 120, 120);
    doc.text(val.toString(), chartX - 8, gridY + 2, { align: "right" });
  }

  // Draw axes
  doc.setDrawColor(100, 100, 100);
  doc.setLineWidth(0.5);
  doc.line(chartX, chartY, chartX, chartY + chartH);
  doc.line(chartX, chartY + chartH, chartX + chartW, chartY + chartH);

  // Draw bars with gradient effect
  for (let m = 1; m <= 12; m++) {
    const val = byMonth[m] ?? 0;
    const barH = (val / maxVal) * chartH;
    const x = chartX + (m - 1) * (chartW / 12) + 3;
    const barY = chartY + chartH - barH;
    
    if (val > 0) {
      // Draw shadow
      doc.setFillColor(200, 200, 200);
      doc.rect(x + 1, barY + 1, barW, barH, "F");
      
      // Draw main bar with gradient colors
      const intensity = val / maxVal;
      const r = Math.round(color.r + (255 - color.r) * (1 - intensity));
      const g = Math.round(color.g + (255 - color.g) * (1 - intensity));
      const b = Math.round(color.b + (255 - color.b) * (1 - intensity));
      doc.setFillColor(r, g, b);
      doc.roundedRect(x, barY, barW, barH, 1, 1, "F");
      
      // Draw border
      doc.setDrawColor(color.r, color.g, color.b);
      doc.setLineWidth(0.5);
      doc.roundedRect(x, barY, barW, barH, 1, 1, "S");
      
      // Value label on top of bar
      doc.setFont("helvetica", "bold");
      doc.setFontSize(8);
      doc.setTextColor(color.r, color.g, color.b);
      doc.text(val.toString(), x + barW / 2, barY - 3, { align: "center" });
    } else {
      // Empty month indicator
      doc.setFillColor(230, 230, 230);
      doc.rect(x, chartY + chartH - 2, barW, 2, "F");
    }
    
    // Month labels
    doc.setFont("helvetica", "normal");
    doc.setFontSize(7);
    doc.setTextColor(80, 80, 80);
    doc.text(MONTHS[m - 1].slice(0, 3), x + barW / 2, chartY + chartH + 6, { align: "center" });
  }

  // Add legend/summary
  const totalActivities = Object.values(byMonth).reduce((sum, val) => sum + val, 0);
  const avgPerMonth = (totalActivities / 12).toFixed(1);
  const activeMonths = Object.keys(byMonth).length;
  
  y = chartY + chartH + 15;
  doc.setFillColor(240, 245, 255);
  doc.roundedRect(chartX, y, chartW, 18, 2, 2, "F");
  
  doc.setFont("helvetica", "bold");
  doc.setFontSize(8);
  doc.setTextColor(60, 60, 60);
  doc.text("Summary:", chartX + 5, y + 6);
  
  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  doc.text(`Total: ${totalActivities} activities`, chartX + 25, y + 6);
  doc.text(`Average: ${avgPerMonth} per month`, chartX + 70, y + 6);
  doc.text(`Active Months: ${activeMonths}/12`, chartX + 130, y + 6);
  
  doc.setFont("helvetica", "italic");
  doc.setFontSize(7);
  doc.setTextColor(100, 100, 100);
  doc.text(`Peak Month: ${MONTHS[Number(Object.entries(byMonth).sort(([, a], [, b]) => b - a)[0]?.[0] ?? 1) - 1]}`, chartX + 5, y + 13);
}

function drawParticipantPieChart(doc: jsPDF, config: ReportConfig, color: RGB, pw: number, ph: number) {
  let y = 28;
  doc.setFont("helvetica", "bold");
  doc.setFontSize(13);
  doc.setTextColor(30, 30, 30);
  doc.text("Participant Distribution by Sector", 10, y);
  
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(100, 100, 100);
  doc.text("Breakdown of participants across different sectors", 10, y + 6);
  y += 15;

  const activities = config.activities;
  const sectors = [
    {
      name: "NGA",
      value: sum(activities, a => a.participants.nga.male + a.participants.nga.female),
      color: { r: 59, g: 130, b: 246 } // Blue
    },
    {
      name: "LGU",
      value: sum(activities, a => a.participants.lgu.male + a.participants.lgu.female),
      color: { r: 16, g: 185, b: 129 } // Green
    },
    {
      name: "SUC",
      value: sum(activities, a => a.participants.suc.male + a.participants.suc.female),
      color: { r: 245, g: 158, b: 11 } // Orange
    },
    {
      name: "Others",
      value: sum(activities, a => a.participants.others.male + a.participants.others.female),
      color: { r: 139, g: 92, b: 246 } // Purple
    },
  ];

  const total = sectors.reduce((sum, s) => sum + s.value, 0);
  if (total === 0) return;

  // Draw pie chart
  const centerX = pw / 3;
  const centerY = y + 40;
  const radius = 35;
  
  let startAngle = -90; // Start from top
  
  sectors.forEach((sector, idx) => {
    const percentage = (sector.value / total) * 100;
    const sliceAngle = (sector.value / total) * 360;
    const endAngle = startAngle + sliceAngle;
    
    if (sector.value > 0) {
      // Draw slice
      doc.setFillColor(sector.color.r, sector.color.g, sector.color.b);
      drawPieSlice(doc, centerX, centerY, radius, startAngle, endAngle);
      
      // Draw slice border
      doc.setDrawColor(255, 255, 255);
      doc.setLineWidth(1);
      drawPieSlice(doc, centerX, centerY, radius, startAngle, endAngle, true);
      
      // Draw percentage label on slice
      if (percentage > 5) {
        const labelAngle = startAngle + sliceAngle / 2;
        const labelRadius = radius * 0.7;
        const labelX = centerX + labelRadius * Math.cos((labelAngle * Math.PI) / 180);
        const labelY = centerY + labelRadius * Math.sin((labelAngle * Math.PI) / 180);
        
        doc.setFont("helvetica", "bold");
        doc.setFontSize(9);
        doc.setTextColor(255, 255, 255);
        doc.text(`${percentage.toFixed(1)}%`, labelX, labelY, { align: "center" });
      }
    }
    
    startAngle = endAngle;
  });

  // Draw center circle for donut effect
  doc.setFillColor(255, 255, 255);
  doc.circle(centerX, centerY, radius * 0.4, "F");
  
  // Total in center
  doc.setFont("helvetica", "bold");
  doc.setFontSize(14);
  doc.setTextColor(60, 60, 60);
  doc.text(total.toLocaleString(), centerX, centerY - 3, { align: "center" });
  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  doc.setTextColor(120, 120, 120);
  doc.text("Total", centerX, centerY + 4, { align: "center" });

  // Legend
  const legendX = pw / 2 + 10;
  let legendY = y + 10;
  
  doc.setFont("helvetica", "bold");
  doc.setFontSize(10);
  doc.setTextColor(60, 60, 60);
  doc.text("Legend", legendX, legendY);
  legendY += 8;

  sectors.forEach((sector, idx) => {
    const percentage = (sector.value / total) * 100;
    
    // Color box
    doc.setFillColor(sector.color.r, sector.color.g, sector.color.b);
    doc.roundedRect(legendX, legendY - 3, 6, 6, 1, 1, "F");
    
    // Sector name
    doc.setFont("helvetica", "bold");
    doc.setFontSize(9);
    doc.setTextColor(60, 60, 60);
    doc.text(sector.name, legendX + 10, legendY + 1);
    
    // Value and percentage
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8);
    doc.setTextColor(100, 100, 100);
    doc.text(`${sector.value.toLocaleString()} (${percentage.toFixed(1)}%)`, legendX + 30, legendY + 1);
    
    legendY += 10;
  });

  // Gender breakdown
  legendY += 5;
  doc.setFont("helvetica", "bold");
  doc.setFontSize(10);
  doc.setTextColor(60, 60, 60);
  doc.text("Gender Distribution", legendX, legendY);
  legendY += 8;

  const totalMale = sum(activities, a => 
    a.participants.nga.male + a.participants.lgu.male + 
    a.participants.suc.male + a.participants.others.male
  );
  const totalFemale = sum(activities, a => 
    a.participants.nga.female + a.participants.lgu.female + 
    a.participants.suc.female + a.participants.others.female
  );

  // Male
  doc.setFillColor(59, 130, 246);
  doc.roundedRect(legendX, legendY - 3, 6, 6, 1, 1, "F");
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(60, 60, 60);
  doc.text(`Male: ${totalMale.toLocaleString()} (${pct(totalMale, total)})`, legendX + 10, legendY + 1);
  
  legendY += 8;
  
  // Female
  doc.setFillColor(236, 72, 153);
  doc.roundedRect(legendX, legendY - 3, 6, 6, 1, 1, "F");
  doc.text(`Female: ${totalFemale.toLocaleString()} (${pct(totalFemale, total)})`, legendX + 10, legendY + 1);
}

function drawProvinceBarChart(doc: jsPDF, config: ReportConfig, color: RGB, pw: number, ph: number) {
  let y = 115;
  doc.setFont("helvetica", "bold");
  doc.setFontSize(13);
  doc.setTextColor(30, 30, 30);
  doc.text("Activities by Province", 10, y);
  
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(100, 100, 100);
  doc.text("Geographic distribution of activities", 10, y + 6);
  y += 12;

  const byProv: Record<string, number> = {};
  for (const a of config.activities) {
    byProv[a.provinceName] = (byProv[a.provinceName] || 0) + 1;
  }

  const sortedProvinces = Object.entries(byProv)
    .sort(([, a], [, b]) => b - a)
    .slice(0, 6); // Top 6 provinces

  if (sortedProvinces.length === 0) return;

  const maxVal = sortedProvinces[0][1];
  const chartX = 20;
  const chartY = y;
  const chartW = pw - 40;
  const barH = 12;
  const spacing = 4;

  sortedProvinces.forEach(([province, count], idx) => {
    const barY = chartY + idx * (barH + spacing);
    const barWidth = (count / maxVal) * (chartW - 80);
    
    // Province name
    doc.setFont("helvetica", "bold");
    doc.setFontSize(9);
    doc.setTextColor(60, 60, 60);
    doc.text(province, chartX, barY + 8);
    
    // Bar background
    doc.setFillColor(240, 240, 240);
    doc.roundedRect(chartX + 70, barY, chartW - 80, barH, 2, 2, "F");
    
    // Bar
    const intensity = count / maxVal;
    const r = Math.round(color.r + (255 - color.r) * (1 - intensity));
    const g = Math.round(color.g + (255 - color.g) * (1 - intensity));
    const b = Math.round(color.b + (255 - color.b) * (1 - intensity));
    doc.setFillColor(r, g, b);
    doc.roundedRect(chartX + 70, barY, barWidth, barH, 2, 2, "F");
    
    // Value label
    doc.setFont("helvetica", "bold");
    doc.setFontSize(9);
    doc.setTextColor(color.r, color.g, color.b);
    doc.text(count.toString(), chartX + 70 + barWidth + 5, barY + 8);
    
    // Percentage
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8);
    doc.setTextColor(120, 120, 120);
    const totalActivities = Object.values(byProv).reduce((sum, val) => sum + val, 0);
    doc.text(`(${((count / totalActivities) * 100).toFixed(1)}%)`, chartX + 70 + barWidth + 15, barY + 8);
  });
}

// Helper function to draw pie slices
function drawPieSlice(
  doc: jsPDF,
  centerX: number,
  centerY: number,
  radius: number,
  startAngle: number,
  endAngle: number,
  strokeOnly: boolean = false
) {
  const startRad = (startAngle * Math.PI) / 180;
  const endRad = (endAngle * Math.PI) / 180;
  
  doc.setLineWidth(strokeOnly ? 1 : 0.1);
  
  // Move to center
  const path: any[] = [];
  path.push({ op: "m", c: [centerX, centerY] });
  
  // Line to start of arc
  path.push({
    op: "l",
    c: [centerX + radius * Math.cos(startRad), centerY + radius * Math.sin(startRad)]
  });
  
  // Draw arc
  const steps = Math.max(Math.ceil(Math.abs(endAngle - startAngle) / 5), 1);
  for (let i = 1; i <= steps; i++) {
    const angle = startRad + ((endRad - startRad) * i) / steps;
    path.push({
      op: "l",
      c: [centerX + radius * Math.cos(angle), centerY + radius * Math.sin(angle)]
    });
  }
  
  // Close path
  path.push({ op: "l", c: [centerX, centerY] });
  
  // Draw the path
  if (strokeOnly) {
    doc.lines(path.map(p => p.c), centerX, centerY, [1, 1], "S");
  } else {
    doc.lines(path.map(p => p.c), centerX, centerY, [1, 1], "F");
  }
}

function hexToRgb(hex: string): RGB {
  return {
    r: parseInt(hex.slice(1, 3), 16),
    g: parseInt(hex.slice(3, 5), 16),
    b: parseInt(hex.slice(5, 7), 16),
  };
}

function sumParticipants(activities: ExportActivity[]): number {
  return activities.reduce((s, a) =>
    s + a.participants.nga.male + a.participants.nga.female +
    a.participants.lgu.male + a.participants.lgu.female +
    a.participants.suc.male + a.participants.suc.female +
    a.participants.others.male + a.participants.others.female, 0);
}

function sum(activities: ExportActivity[], fn: (a: ExportActivity) => number): number {
  return activities.reduce((s, a) => s + fn(a), 0);
}

function pct(val: number, total: number): string {
  if (total === 0) return "0%";
  return ((val / total) * 100).toFixed(1) + "%";
}

function formatDate(d: Date): string {
  return d.toLocaleDateString("en-PH", { year: "numeric", month: "long", day: "numeric" });
}

function buildFilename(config: ReportConfig, project: ReturnType<typeof DICT_PROJECTS.find>): string {
  const proj = project?.shortName ?? "Consolidated";
  const prov = config.provinceName ? `_${config.provinceName.replace(/\s+/g, "_")}` : "";
  const fy = config.fy.replace(/\s+/g, "_");
  return `DICT_R5_${proj}${prov}_${fy}_Report.pdf`;
}
