// ============================================================
// PDF Report Generator � DICT Region V PMS
// ============================================================

import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import { ExportActivity } from "./google-sheets";
import { DICT_PROJECTS, MONTHS } from "./types";

export interface ReportConfig {
  title: string;
  subtitle?: string;
  projectCode?: string;
  provinceName?: string;
  fy: string;
  periodLabel: string;
  activities: ExportActivity[];
  generatedBy: string;
  generatedAt: Date;
}

export interface GeneratedReport {
  blob: Blob;
  filename: string;
}

interface RGB { r: number; g: number; b: number }

export async function generatePDFReport(config: ReportConfig): Promise<GeneratedReport> {
  const doc = new jsPDF({ orientation: "landscape", unit: "mm", format: "a4" });
  const project = config.projectCode ? DICT_PROJECTS.find(p => p.code === config.projectCode) : null;
  const primaryColor = hexToRgb(project?.color ?? "#1a56db");
  const PAGE_W = doc.internal.pageSize.getWidth();
  const PAGE_H = doc.internal.pageSize.getHeight();

  drawCoverPage(doc, config, project, primaryColor, PAGE_W, PAGE_H);
  doc.addPage();
  drawHeader(doc, config, project, primaryColor, PAGE_W);
  drawExecutiveSummary(doc, config, primaryColor, PAGE_W);

  if (config.activities.length > 0) {
    doc.addPage();
    drawHeader(doc, config, project, primaryColor, PAGE_W);
    drawActivitiesTable(doc, config, primaryColor);
  }

  doc.addPage();
  drawHeader(doc, config, project, primaryColor, PAGE_W);
  drawParticipantBreakdown(doc, config, primaryColor);

  doc.addPage();
  drawHeader(doc, config, project, primaryColor, PAGE_W);
  drawByProvinceSummary(doc, config, primaryColor);

  doc.addPage();
  drawHeader(doc, config, project, primaryColor, PAGE_W);
  drawByMonthChart(doc, config, primaryColor, PAGE_W, PAGE_H);

  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    drawFooter(doc, config, i, pageCount, PAGE_W, PAGE_H);
  }

  const filename = buildFilename(config, project);
  return { blob: doc.output("blob"), filename };
}

function drawCoverPage(doc: jsPDF, config: ReportConfig, project: ReturnType<typeof DICT_PROJECTS.find>, color: RGB, pw: number, ph: number) {
  doc.setFillColor(color.r, color.g, color.b);
  doc.rect(0, 0, pw, 60, "F");
  doc.setFillColor(255, 255, 255);
  doc.circle(20, 30, 12, "F");
  doc.setFont("helvetica", "bold");
  doc.setFontSize(7);
  doc.setTextColor(color.r, color.g, color.b);
  doc.text("DICT", 20, 30, { align: "center", baseline: "middle" });
  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.text("Republic of the Philippines", 37, 22);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(13);
  doc.text("Department of Information and Communications Technology", 37, 30);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.text("Region V � Bicol", 37, 38);

  doc.setTextColor(40, 40, 40);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(24);
  doc.text(config.title, pw / 2, 90, { align: "center" });
  if (config.subtitle) {
    doc.setFont("helvetica", "normal");
    doc.setFontSize(14);
    doc.setTextColor(80, 80, 80);
    doc.text(config.subtitle, pw / 2, 102, { align: "center" });
  }

  if (project) {
    const badgeW = 80;
    doc.setFillColor(color.r, color.g, color.b);
    doc.roundedRect((pw - badgeW) / 2, 112, badgeW, 12, 4, 4, "F");
    doc.setTextColor(255, 255, 255);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(10);
    doc.text(project.name, pw / 2, 119, { align: "center" });
  }

  const boxes = [
    { label: "Fiscal Year", value: config.fy },
    { label: "Period", value: config.periodLabel },
    { label: "Province", value: config.provinceName ?? "All Provinces" },
    { label: "Total Activities", value: config.activities.length.toString() },
  ];
  const boxW = (pw - 40) / boxes.length;
  boxes.forEach((box, i) => {
    const x = 20 + i * boxW;
    doc.setFillColor(248, 249, 250);
    doc.roundedRect(x, 140, boxW - 4, 28, 3, 3, "F");
    doc.setDrawColor(color.r, color.g, color.b);
    doc.roundedRect(x, 140, boxW - 4, 28, 3, 3, "S");
    doc.setTextColor(100, 100, 100);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8);
    doc.text(box.label, x + (boxW - 4) / 2, 149, { align: "center" });
    doc.setTextColor(30, 30, 30);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(13);
    doc.text(box.value, x + (boxW - 4) / 2, 161, { align: "center" });
  });

  doc.setFont("helvetica", "italic");
  doc.setFontSize(8);
  doc.setTextColor(140, 140, 140);
  doc.text(`Generated by: ${config.generatedBy} | ${formatDate(config.generatedAt)}`, pw / 2, ph - 15, { align: "center" });
}

function drawHeader(doc: jsPDF, config: ReportConfig, project: ReturnType<typeof DICT_PROJECTS.find>, color: RGB, pw: number) {
  doc.setFillColor(color.r, color.g, color.b);
  doc.rect(0, 0, pw, 18, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(9);
  doc.text("DICT Region V � " + (project?.name ?? "Consolidated Report"), 10, 11);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  doc.text(config.periodLabel + " | " + config.fy, pw - 10, 11, { align: "right" });
}

function drawFooter(doc: jsPDF, config: ReportConfig, page: number, total: number, pw: number, ph: number) {
  doc.setDrawColor(200, 200, 200);
  doc.line(10, ph - 12, pw - 10, ph - 12);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(7);
  doc.setTextColor(140, 140, 140);
  doc.text("DICT Region V Program Management System", 10, ph - 7);
  doc.text(`Page ${page} of ${total}`, pw - 10, ph - 7, { align: "right" });
}

function drawExecutiveSummary(doc: jsPDF, config: ReportConfig, color: RGB, pw: number) {
  const activities = config.activities;
  const totalPax = sumParticipants(activities);
  const provinces = [...new Set(activities.map(a => a.provinceName))];
  let y = 28;

  doc.setFont("helvetica", "bold");
  doc.setFontSize(13);
  doc.setTextColor(30, 30, 30);
  doc.text("Executive Summary", 10, y);
  y += 10;

  const kpis = [
    { label: "Total Activities", value: activities.length },
    { label: "Total Participants", value: totalPax },
    { label: "Provinces", value: provinces.length },
    { label: "LGUs", value: [...new Set(activities.map(a => a.lguName).filter(Boolean))].length },
    { label: "Validated/Reported", value: activities.filter(a => a.status === "Validated" || a.status === "Reported").length },
  ];
  const cardW = (pw - 20) / kpis.length - 2;
  kpis.forEach((kpi, i) => {
    const x = 10 + i * (cardW + 2);
    doc.setFillColor(color.r, color.g, color.b);
    doc.roundedRect(x, y, cardW, 22, 2, 2, "F");
    doc.setTextColor(255, 255, 255);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(16);
    doc.text(kpi.value.toLocaleString(), x + cardW / 2, y + 12, { align: "center" });
    doc.setFont("helvetica", "normal");
    doc.setFontSize(7);
    doc.text(kpi.label, x + cardW / 2, y + 18, { align: "center" });
  });
  y += 30;

  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.setTextColor(30, 30, 30);
  doc.text("Participant Breakdown by Sector", 10, y);
  y += 4;

  const ngaM = sum(activities, a => a.participants.nga.male);
  const ngaF = sum(activities, a => a.participants.nga.female);
  const lguM = sum(activities, a => a.participants.lgu.male);
  const lguF = sum(activities, a => a.participants.lgu.female);
  const sucM = sum(activities, a => a.participants.suc.male);
  const sucF = sum(activities, a => a.participants.suc.female);
  const othM = sum(activities, a => a.participants.others.male);
  const othF = sum(activities, a => a.participants.others.female);

  autoTable(doc, {
    startY: y,
    head: [["Sector", "Male", "Female", "Total", "% of Total"]],
    body: [
      ["NGA", ngaM, ngaF, ngaM + ngaF, pct(ngaM + ngaF, totalPax)],
      ["LGU", lguM, lguF, lguM + lguF, pct(lguM + lguF, totalPax)],
      ["SUC", sucM, sucF, sucM + sucF, pct(sucM + sucF, totalPax)],
      ["Others", othM, othF, othM + othF, pct(othM + othF, totalPax)],
      ["TOTAL", ngaM + lguM + sucM + othM, ngaF + lguF + sucF + othF, totalPax, "100%"],
    ],
    styles: { fontSize: 9, cellPadding: 3 },
    headStyles: { fillColor: [color.r, color.g, color.b], textColor: [255, 255, 255], fontStyle: "bold" },
    alternateRowStyles: { fillColor: [248, 248, 248] },
    margin: { left: 10, right: 10 },
  });
}

function drawActivitiesTable(doc: jsPDF, config: ReportConfig, color: RGB) {
  let y = 28;
  doc.setFont("helvetica", "bold");
  doc.setFontSize(13);
  doc.setTextColor(30, 30, 30);
  doc.text("Activity Records", 10, y);

  const rows = config.activities.map(a => {
    const total =
      a.participants.nga.male + a.participants.nga.female +
      a.participants.lgu.male + a.participants.lgu.female +
      a.participants.suc.male + a.participants.suc.female +
      a.participants.others.male + a.participants.others.female;
    return [
      MONTHS[a.month - 1]?.slice(0, 3) ?? a.month,
      a.provinceName, a.lguName ?? "�",
      a.activityTitle.length > 35 ? a.activityTitle.slice(0, 35) + "�" : a.activityTitle,
      a.venue.length > 25 ? a.venue.slice(0, 25) + "�" : a.venue,
      a.modeOfConduct, total.toLocaleString(), a.status,
    ];
  });

  autoTable(doc, {
    startY: y + 4,
    head: [["Month", "Province", "LGU", "Activity Title", "Venue", "Mode", "Participants", "Status"]],
    body: rows,
    styles: { fontSize: 7.5, cellPadding: 2.5, overflow: "linebreak" },
    headStyles: { fillColor: [color.r, color.g, color.b], textColor: [255, 255, 255], fontStyle: "bold" },
    alternateRowStyles: { fillColor: [248, 248, 250] },
    columnStyles: {
      0: { cellWidth: 14 }, 1: { cellWidth: 22 }, 2: { cellWidth: 25 },
      3: { cellWidth: 60 }, 4: { cellWidth: 45 }, 5: { cellWidth: 22 },
      6: { cellWidth: 20, halign: "right" }, 7: { cellWidth: 20 },
    },
    margin: { left: 10, right: 10 },
  });
}

function drawParticipantBreakdown(doc: jsPDF, config: ReportConfig, color: RGB) {
  let y = 28;
  doc.setFont("helvetica", "bold");
  doc.setFontSize(13);
  doc.setTextColor(30, 30, 30);
  doc.text("Participant Breakdown by Activity", 10, y);

  const rows = config.activities.map(a => {
    const p = a.participants;
    const total = p.nga.male + p.nga.female + p.lgu.male + p.lgu.female +
      p.suc.male + p.suc.female + p.others.male + p.others.female;
    return [
      a.activityTitle.length > 30 ? a.activityTitle.slice(0, 30) + "�" : a.activityTitle,
      a.provinceName,
      p.nga.male, p.nga.female, p.lgu.male, p.lgu.female,
      p.suc.male, p.suc.female, p.others.male, p.others.female, total,
    ];
  });

  autoTable(doc, {
    startY: y + 4,
    head: [["Activity", "Province", "NGA M", "NGA F", "LGU M", "LGU F", "SUC M", "SUC F", "Oth M", "Oth F", "Total"]],
    body: rows,
    styles: { fontSize: 7, cellPadding: 2, halign: "center" },
    headStyles: { fillColor: [color.r, color.g, color.b], textColor: [255, 255, 255], fontStyle: "bold" },
    alternateRowStyles: { fillColor: [248, 248, 250] },
    columnStyles: { 0: { halign: "left", cellWidth: 65 }, 1: { halign: "left", cellWidth: 25 }, 10: { fontStyle: "bold" } },
    margin: { left: 10, right: 10 },
  });
}

function drawByProvinceSummary(doc: jsPDF, config: ReportConfig, color: RGB) {
  let y = 28;
  doc.setFont("helvetica", "bold");
  doc.setFontSize(13);
  doc.setTextColor(30, 30, 30);
  doc.text("Summary by Province", 10, y);

  const byProv: Record<string, { count: number; participants: number }> = {};
  for (const a of config.activities) {
    if (!byProv[a.provinceName]) byProv[a.provinceName] = { count: 0, participants: 0 };
    byProv[a.provinceName].count++;
    byProv[a.provinceName].participants +=
      a.participants.nga.male + a.participants.nga.female +
      a.participants.lgu.male + a.participants.lgu.female +
      a.participants.suc.male + a.participants.suc.female +
      a.participants.others.male + a.participants.others.female;
  }
  const total = Object.values(byProv).reduce((s, v) => ({ count: s.count + v.count, participants: s.participants + v.participants }), { count: 0, participants: 0 });
  const rows = Object.entries(byProv).map(([prov, d]) => [prov, d.count, d.participants.toLocaleString(), pct(d.count, total.count), pct(d.participants, total.participants)]);

  autoTable(doc, {
    startY: y + 4,
    head: [["Province", "Activities", "Participants", "% Activities", "% Participants"]],
    body: rows,
    foot: [["TOTAL", total.count, total.participants.toLocaleString(), "100%", "100%"]],
    styles: { fontSize: 9, cellPadding: 3 },
    headStyles: { fillColor: [color.r, color.g, color.b], textColor: [255, 255, 255], fontStyle: "bold" },
    footStyles: { fillColor: [240, 240, 240], fontStyle: "bold" },
    alternateRowStyles: { fillColor: [248, 248, 248] },
    margin: { left: 10, right: 10 },
  });
}

function drawByMonthChart(doc: jsPDF, config: ReportConfig, color: RGB, pw: number, ph: number) {
  let y = 28;
  doc.setFont("helvetica", "bold");
  doc.setFontSize(13);
  doc.setTextColor(30, 30, 30);
  doc.text("Monthly Activity Count", 10, y);
  y += 8;

  const byMonth: Record<number, number> = {};
  for (const a of config.activities) { byMonth[a.month] = (byMonth[a.month] || 0) + 1; }
  const maxVal = Math.max(...Object.values(byMonth), 1);
  const chartX = 20, chartY = y, chartW = pw - 40, chartH = 60;
  const barW = chartW / 12 - 4;

  doc.setDrawColor(180, 180, 180);
  doc.line(chartX, chartY, chartX, chartY + chartH);
  doc.line(chartX, chartY + chartH, chartX + chartW, chartY + chartH);

  for (let m = 1; m <= 12; m++) {
    const val = byMonth[m] ?? 0;
    const barH = (val / maxVal) * chartH;
    const x = chartX + (m - 1) * (chartW / 12) + 2;
    const barY = chartY + chartH - barH;
    if (val > 0) {
      doc.setFillColor(color.r, color.g, color.b);
      doc.rect(x, barY, barW, barH, "F");
      doc.setFont("helvetica", "bold");
      doc.setFontSize(7);
      doc.setTextColor(color.r, color.g, color.b);
      doc.text(val.toString(), x + barW / 2, barY - 2, { align: "center" });
    } else {
      doc.setFillColor(220, 220, 220);
      doc.rect(x, chartY + chartH - 1, barW, 1, "F");
    }
    doc.setFont("helvetica", "normal");
    doc.setFontSize(7);
    doc.setTextColor(100, 100, 100);
    doc.text(MONTHS[m - 1].slice(0, 3), x + barW / 2, chartY + chartH + 5, { align: "center" });
  }
}

function hexToRgb(hex: string): RGB {
  return {
    r: parseInt(hex.slice(1, 3), 16),
    g: parseInt(hex.slice(3, 5), 16),
    b: parseInt(hex.slice(5, 7), 16),
  };
}

function sumParticipants(activities: ExportActivity[]): number {
  return activities.reduce((s, a) =>
    s + a.participants.nga.male + a.participants.nga.female +
    a.participants.lgu.male + a.participants.lgu.female +
    a.participants.suc.male + a.participants.suc.female +
    a.participants.others.male + a.participants.others.female, 0);
}

function sum(activities: ExportActivity[], fn: (a: ExportActivity) => number): number {
  return activities.reduce((s, a) => s + fn(a), 0);
}

function pct(val: number, total: number): string {
  if (total === 0) return "0%";
  return ((val / total) * 100).toFixed(1) + "%";
}

function formatDate(d: Date): string {
  return d.toLocaleDateString("en-PH", { year: "numeric", month: "long", day: "numeric" });
}

function buildFilename(config: ReportConfig, project: ReturnType<typeof DICT_PROJECTS.find>): string {
  const proj = project?.shortName ?? "Consolidated";
  const prov = config.provinceName ? `_${config.provinceName.replace(/\s+/g, "_")}` : "";
  const fy = config.fy.replace(/\s+/g, "_");
  return `DICT_R5_${proj}${prov}_${fy}_Report.pdf`;
}
